version: '3.9'

services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./api/app:/app
    ports:
      - "8000:8000"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/usr/src/app      
    command: sh -c "cd fx-chart && yarn start"

    ports:
      - "3000:3000"
    stdin_open: true 
    tty: true
