version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./backend/app:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/reactApp:/usr/src/app
    command: sh -c "cd react-sample && yarn start"

    ports:
      - "3000:3000"
    stdin_open: true 
    tty: true
